apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbvolume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/lib/postgresql/data1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbvolume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: dbvolume

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbvolume
  labels:
    app: dbvolume
spec:
  selector:
    matchLabels:
      app: dbvolume
  replicas: 1
  template:
    metadata:
      labels:
        app: dbvolume
    spec:
      containers:
        - name: dbvolume
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: john
            - name: POSTGRES_PASSWORD
              value: example
            - name: POSTGRES_DB
              value: endgame
            - name: DB_HOST
              value: db
          volumeMounts:
            - name: dbvolume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: dbvolume
          persistentVolumeClaim:
            claimName: dbvolume
---
apiVersion: v1
kind: Service
metadata:
  name: dbvolume
spec:
  type: NodePort
  selector:
    app: dbvolume
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30000  # Specify a desired NodePort number
